# Generated by Django 3.2.2 on 2021-05-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='You',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_Major', models.CharField(max_length=200)),
                ('your_Favorite', models.CharField(max_length=100)),
                ('your_Gender', models.CharField(max_length=200)),
                ('your_Birthday', models.DateTimeField()),
                ('introduce_me_to_you', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
